version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.12
    steps:
      -checkout
      -run: python main.py
    test:
      docker:
        - image: cimg/python:3.12
      steps:
        -checkout
        -run: python test.py
    deploy:
      - image: cimg/python:3.12
    steps:
      - run: echo "Practical Done"

workflows:
  build and test deploy:
    jobs:
      -build
      -test:
          requires:
            -build
      -deploy:
        requires:
          -test
        filters:
          branches:
            only: main